add HF token support through params
substratusai/images pull request #13
Opened 2023-07-26 06:45 UTC by samos123

2023-07-26 07:40 UTC, brandonjbjelland approved these changes
LGTM but I bet Nick has an opinion here.

2023-07-26 13:46 UTC, nstogner requested changes

2023-07-26 13:46 UTC, nstogner commented on base/Dockerfile
> +ENTRYPOINT ["/tini", "--", "HUGGING_FACE_HUB_TOKEN=$PARAM_HUGGING_FACE_HUB_TOKEN"]
I would prefer to keep huggingface-things in the huggingface containers only.

2023-07-27 05:04 UTC, samos123 commented on base/Dockerfile
> +ENTRYPOINT ["/tini", "--", "HUGGING_FACE_HUB_TOKEN=$PARAM_HUGGING_FACE_HUB_TOKEN"]
done, please review again

2023-07-27 05:29 UTC, samos123 commented
1 thing to note, I might file a new issue for it, our pods dont automatically pull down latest if the image was already found on the node:
```
  Normal  Pulled     8s    kubelet                                Container image "substratusai/model-loader-huggingface:pr-13" already present on machine

```

2023-07-27 05:33 UTC, brandonjbjelland approved these changes
🐼

2023-07-27 12:42 UTC, nstogner commented on model-loader-huggingface/Dockerfile
> +ENTRYPOINT ["/tini", "--", "/content/scripts/entrypoint.sh"]
Will we still get all of the benefits of tini (catching shutdown signals and passing them along?) if we call a script that calls a script that calls a executable?

2023-07-27 15:02 UTC, samos123 commented on model-loader-huggingface/Dockerfile
> +ENTRYPOINT ["/tini", "--", "/content/scripts/entrypoint.sh"]
Hmm good question. I need to test that.

2023-07-28 02:53 UTC, samos123 commented on model-loader-huggingface/Dockerfile
> +ENTRYPOINT ["/tini", "--", "/content/scripts/entrypoint.sh"]
I tested it by creating a python program that handles sigterm and then ran it in the image:
```
docker run -ti -v ./src:/content/src substratusai/model-loader-huggingface:pr-13 python3 /content/src/sig-handler.py
doing something in a loop ..
doing something in a loop ...
doing something in a loop ...
doing something in a loop ...
End of the program. I was killed gracefully :)
```

Then I killed the tini process
```
╭─samos@asus-arch ~/workspace/substratus-images/model-loader-huggingface ‹hf-token●› 
╰─$ ps aux | grep sig-handler
samos      95393  0.1  0.1 1327996 24928 pts/4   Sl+  19:51   0:00 docker run -ti -v ./src:/content/src substratusai/model-loader-huggingface:pr-13 python3 /content/src/sig-handler.py
root       95591  0.2  0.0   2776  1152 pts/0    Ss   19:51   0:00 /tini -- /content/scripts/entrypoint.sh python3 /content/src/sig-handler.py
root       95613  0.1  0.0  13540  8192 pts/0    S+   19:51   0:00 python3 /content/src/sig-handler.py
samos      95619  0.0  0.0   6580  2532 pts/6    S+   19:51   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox sig-handler
╭─samos@asus-arch ~/workspace/substratus-images/model-loader-huggingface ‹hf-token●› 
╰─$ kill 95591
kill: kill 95591 failed: operation not permitted
╭─samos@asus-arch ~/workspace/substratus-images/model-loader-huggingface ‹hf-token●› 
╰─$ sudo kill 95591                                                                
```
It all seemed to work as expected. Not sure what else to test. I'm gonna merge this.

This is the sig handler.py file I used:
```
import signal
import time

class GracefulKiller:
  kill_now = False
  def __init__(self):
    signal.signal(signal.SIGINT, self.exit_gracefully)
    signal.signal(signal.SIGTERM, self.exit_gracefully)

  def exit_gracefully(self, *args):
    self.kill_now = True

if __name__ == '__main__':
  killer = GracefulKiller()
  while not killer.kill_now:
    time.sleep(1)
    print("doing something in a loop ...")

  print("End of the program. I was killed gracefully :)")
```

2023-07-28 02:55 UTC, merged